import axios from "axios";
import Orders from "../../Components/OrderHistoryPage/Orders";
import DisplayPaths from "../../Components/Shared/DisplayPaths";
import Head from "next/head";
import { useRouter } from "next/router";

const Handler = ({ result }) => {
  console.log("order history page 8", result);
  const router = useRouter();
  const email = router?.query?.email;
  const filteredResult = result?.filter((el) => el?.email === email);
  return (
    <>
      {/* head  */}
      <Head>
        <title>Male Fashion - Order History</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <DisplayPaths
          heading={"order history"}
          paths={["home", "order history"]}
        />
        <div className="w-[100vw] lg:w-[1170px] px-[.5rem] lg:px-0 mx-auto min-h-[45vh]">
          <div className="lg:w-[50%] mx-auto flex flex-col gap-[2.5rem]">
            {filteredResult?.length ? (
              filteredResult?.map((order) => (
                <Orders key={order?._id} order={order} />
              ))
            ) : (
              <p className="text-center text-[22px] tracking-wide text-[dimgray]">{`You didn't any order before.`}</p>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default Handler;

export async function getStaticProps() {
  try {
    const {
      data: { data },
    } = await axios.get(`https://male-fashion1.netlify.app/api/loadorders`);
    return {
      props: {
        result: data,
      },
      revalidate: 1,
    };
  } catch (err) {
    console.log("load order page 51", err.message);
    return {
      props: {
        result: [],
      },
    };
  }
}
