import Image from "next/image";
import failedGif from "../Assets/Icon/failed.gif";
import Link from "next/link";
import { BiHome } from "react-icons/bi";
import Head from "next/head";

const Handler = () => {
  return (
    <>
      {/* head  */}
      <Head>
        <title>Payment - Failed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center items-center min-h-[80vh]">
        <div className="flex flex-col items-center gap-[1rem] relative">
          <div className="w-[150px] h-[150px] relative">
            <Image
              priority
              className="object-cover"
              src={failedGif}
              layout="fill"
              alt="failed-gif"
            />
          </div>
          <div className="flex flex-col items-center mt-[1rem]">
            <p className="mt-[1rem] text-red-600 text-[1.3rem] font-semibold text-center font-mono">
              Unsuccessful Payment
            </p>
            <Link href={"/"}>
              <button className="text-gray-600 font-bold tracking-wider flex items-center gap-[.5rem] mt-[1rem]">
                <BiHome className="text-[1.2rem] translate-y-[-.1rem]" /> Go To
                HomePage
              </button>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
};

export default Handler;
