import Head from "next/head";
import Image from "next/image";
import { useContext, useEffect } from "react";
import { ProductsContext } from "./_app";
import Banner from "../Components/Homepage/Banner";
import Cards from "../Components/Homepage/Cards";
import DiscountOffer from "../Components/Homepage/DiscountOffer";
import LatestNews from "../Components/Homepage/LatestNews";
import Carousel from "../Components/Homepage/Carousel";
import { useRecoilState } from "recoil";
import { productState } from "../AtomStates/ProductStates";

export default function Home({ data }) {
  // const [products, setAllProducts] = useRecoilState(productState);
  // useEffect(() => {
  //   setAllProducts(data);
  // });
  return (
    <div>
      {/* head  */}
      <Head>
        <title>Male Fashion - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* main  */}
      <main className="overflow-hidden">
        <Carousel />
        <Banner />
        <Cards products={data} />
        <DiscountOffer />
        <LatestNews />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  try {
    const res = await fetch(
      `https://male-fashion1.netlify.app/api/loadproducts`
    );
    const data = await res.json();
    return {
      props: {
        data,
      },
    };
  } catch (err) {
    toast.error(err.message, {
      style: {
        border: "1px solid red",
        padding: "16px",
        color: "red",
        background: "whitesmoke",
      },
      iconTheme: {
        primary: "red",
        secondary: "#FFFAEE",
      },
    });
  }
}
