import Head from 'next/head'
import Image from 'next/image'
import { useContext, useEffect } from 'react';
import { ProductsContext } from './_app';

export default function Home({ data }) {
  const { products, setAllProducts } = useContext(ProductsContext);
  useEffect(() => {
    setAllProducts(data)
  })
  return (
    <div>
      {/* head  */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <span>h3llo world</span>
      </main>

      {/* footer  */}
      <footer>
        
      </footer>
    </div>
  )
}


export async function getServerSideProps(){
  const res = await fetch("http://localhost:3000/api/loadproducts");
  const data = await res.json();
  
  return {
    props: {
      data
    }
  }
}